CREATE TABLE IF NOT EXISTS COMMENT (
  id SERIAL PRIMARY KEY,
  comment TEXT NOT NULL,
  likes int DEFAULT 0,
  userId uuid REFERENCES CUSTOMER(id) ON DELETE CASCADE,
  postId int REFERENCES POST(id) ON DELETE CASCADE,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp
)