CREATE TABLE IF NOT EXISTS COMMENT (
  id SERIAL PRIMARY KEY,
  comment TEXT NOT NULL,
  userId REFERENCES CUSTOMER(id) ON DELETE CASCADE,
  postId REFERENCES POST(id) ON DELETE CASCADE,
  createdAt TIMESTAMP DEFAULT current_timestamp,
  
)