CREATE TABLE IF NOT EXISTS Post(
  id SERIAL PRIMARY KEY,
  post TEXT NOT NULL,
  userid uuid REFERENCES Customer(id) ON DELETE CASCADE,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)