CREATE TABLE IF NOT EXISTS Post(
  id SERIAL PRIMARY KEY,
  post TEXT NOT NULL,
  likes INT DEFAULT 0,
  userid uuid REFERENCES Customer(id) ON DELETE CASCADE,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)